// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfuk_E2EEDnosmT_TKzODMpQFyGGaAfqI',
    appId: '1:823659825483:web:54171b4ebd4ddb1156c0ce',
    messagingSenderId: '823659825483',
    projectId: 'submissionditonton',
    authDomain: 'submissionditonton.firebaseapp.com',
    storageBucket: 'submissionditonton.appspot.com',
    measurementId: 'G-DC61KNQZ1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIap9zfuyr8G-xx11YWr_pOTFcj6ywSaw',
    appId: '1:823659825483:android:c6df0cb1fddb012b56c0ce',
    messagingSenderId: '823659825483',
    projectId: 'submissionditonton',
    storageBucket: 'submissionditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnRh6Fui0GtuXzHUQjSu5G_bwMIbWPE8',
    appId: '1:823659825483:ios:2236f698558cf31356c0ce',
    messagingSenderId: '823659825483',
    projectId: 'submissionditonton',
    storageBucket: 'submissionditonton.appspot.com',
    iosClientId: '823659825483-hk4gqg8c8lmg1ivgrai3e3sr2vqdpgid.apps.googleusercontent.com',
    iosBundleId: 'com.example.submissionDitonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWnRh6Fui0GtuXzHUQjSu5G_bwMIbWPE8',
    appId: '1:823659825483:ios:2236f698558cf31356c0ce',
    messagingSenderId: '823659825483',
    projectId: 'submissionditonton',
    storageBucket: 'submissionditonton.appspot.com',
    iosClientId: '823659825483-hk4gqg8c8lmg1ivgrai3e3sr2vqdpgid.apps.googleusercontent.com',
    iosBundleId: 'com.example.submissionDitonton',
  );
}
